FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl3

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY prisma ./prisma/
RUN npx prisma generate

EXPOSE 3001

CMD ["pnpm", "dev"]
